version: '3'
services:
  proxy:
    build: .
    depends_on: 
      - frontend
    ports:
      - 80:80

  frontend:
    image: mshallom/stage2_frontend:latest
    depends_on:
      - backend
    ports:
      - 3000:80

  backend:
    image: mshallom/stage2_backend:latest
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000